name: Build & Deploy Event app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy EventManagementSystem
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        options: --health-cmd='mysqladmin ping --silent' --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: event_management_system_db
          # Remove MYSQL_ROOT_PASSWORD since no password is needed
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' # Allow MySQL to run without a password

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Wait for MySQL to start
        run: |
          until mysqladmin ping --host=localhost --port=3306 --user=root --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 10
          done

      - name: Run Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the Event App
        run: |
          mvn clean
          mvn -B package --file pom.xml
