name: Build & Deploy Event App

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy EventManagementSystem
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Download JUnit Platform Console Standalone
        run: |
          wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.0/junit-platform-console-standalone-1.8.0.jar
          # If you're using a different version, make sure to update the URL accordingly

      - name: Run Unit Tests
        run: |
          java -jar junit-platform-console-standalone-1.8.0.jar --class-path target/test-classes --scan-class-path

      - name: Build the Event App
        run: ./mvnw clean package
