name: Build & Deploy Event App

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy EventManagementSystem
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Run Unit Tests
        run: |
          java -jar junit-platform-console-standalone-1.8.0.jar --class-path target/test-classes --scan-class-path # Modify the jar version as per your needs
          
      - name: Build the Event App
        run: mvn clean package --file pom.xml
