name: Build & Deploy Event app

# when to trigger this action

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy EventManagementSystem
    runs-on: ubuntu-latest
    steps:
        #checkout the code
      - name: Check the code
        # uses means we want to checkout some actions available on: https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v3

        #set up our JDK 17 on our runner
      - name: Setting up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
        # run the tests
      - name: Unit Testing
        run: mvn -B --no-transfer-progress test --file pom.xml

      #package and build
      - name: Build the Event App
        run: |  # when you have multiple commands
          mvn clean
          mvn -B package --file pom.xml