name: Build & Deploy Event app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy EventManagementSystem
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: 
          MYSQL_DATABASE: event_management_system_db
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          
    steps:
      # Checkout code
      - name: Check out the code
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Setting up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      # Wait for MySQL to be ready
      - name: Wait for MySQL
        run: |
          until mysqladmin ping --host=localhost --port=3306 --user=root --password= --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      # Run Unit Tests
      - name: Run Unit Tests
        run: mvn -B test --file pom.xml

      # Build the application
      - name: Build the Event App
        run: |
          mvn clean
          mvn -B package --file pom.xml
